### ISSUE TITLE
Request for data pre-process scripts

### ISSUE THREAD

**Issue by zhanhl316** [dair-iitd/FloNet#1]
Hi, 

   May I request for the data pre-process scripts, from orignial data (https://github.com/dair-iitd/FloDial) to the processed data that could be feeded into retriever.py ? Thank you

Best,

**Comment by ashantanu** [comment]
Hi @zhanhl316 
I have added cached pickle files for both S-Flo and U-Flo split along with model checkpoints. These cached files have the preprocessed data and let you skip the proxy labeling part so that you can get started with the code right away. I will add the preprocessing script soon as well. 

Thanks for your interest in this work!

**Comment by zhanhl316** [comment]
Thank you for your help! Looking forward to your pre-processing scripts. Many thanks!

**Comment by YovaKem** [comment]
I would appreciate the data preprocessing scripts as well.

**Comment by YovaKem** [comment]
Since you have not released the scripts for data preprocessing, can you instead explain what the contexts of the preprocessed data files are, such that I can write my own script? Thanks.

**Comment by ashantanu** [comment]
Hi @YovaKem , I have just pushed the preprocessing file. Sorry that it took so long. The script just reformats the jsons, constructs data for each split using the dialog ids and so on. Please refer to the [script](https://github.com/dair-iitd/FloNet/blob/main/code/preprocess_dataset.py) for more details. Thanks for your patience!

**Comment by YovaKem** [comment]
Thanks. One thing you might want to change is [this](https://github.com/dair-iitd/FloNet/blob/c257874e3d9bfce856b40c2868ef229d6646d407/code/flonet.py#L187) line, which breaks because no test data has been cached, so there's only three values to unpack.
