### ISSUE TITLE
Missing data for flonet.py

### ISSUE THREAD

**Issue by YovaKem** [dair-iitd/FloNet#2]
Hi, when I try running `flonet.py` I run into the problem that neither `../data/saved_data/cached_in_domain_dialogs_score_FAQ.pkl` nor `../data/flowcharts/` exist so `get_dataset_and_batches()` cannot run, i.e. the data cannot be loaded.

**Comment by ashantanu** [comment]
Hi, thanks for raising this. The filename was incorrect in the argument. It has been corrected to the one present in `data/saved_data`. Please note that you should provide the model checkpoints for retriever and generator using the `--retriever_checkpoint` and `--gpt_model_checkpoint` argument.
