### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by YovaKem** [dair-iitd/FloNet#3]
The inference code throws error

```
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

with versions 1.10.2 and 1.7.1 when ran on GPU.

Version 1.5.0 seems to be working fine.

**Comment by ashantanu** [comment]
Good catch. We are using pytorch version 1.6.0 
I'll update the requirements accordingly. Thanks.
