### ISSUE TITLE
glob variable not defined in retriever.py

### ISSUE THREAD

**Issue by YovaKem** [dair-iitd/FloNet#4]
This [line](https://github.com/dair-iitd/FloNet/blob/97604397dd680ee290bd57ea1ac027c6ccf1a419/code/retriever.py#L107) cannot run since `glob` has not been defined yet.

**Comment by Dr-Corgi** [comment]
Same issue. It seems that the ``` glob ``` variable is used in Line 365 in func ```parse_args()```, while ```glob``` is initialized in Line 367.

**Comment by ashantanu** [comment]
Thanks for bringing this up. Moved this assignment to `load_data` function. That function has the `glob` variable.
